getappmap/appmap-node

- jest.config.js
- src/Recording.ts
- src/__tests__/Recording.test.ts
- src/__tests__/helpers.ts
- src/__tests__/recorder.test.ts
- src/recorder.ts
- test/__snapshots__/simple.test.ts.snap
- test/helpers.ts
- test/simple/index.js
This change adds `eventUpdates` to fix up return values and times of promises which are still pending at return time, for example:
```json
{
"events": [
{
"event": "return",
"thread_id": 0,
"id": 4,
"parent_id": 3,
"return_value": {
"class": "Promise",
"value": "Promise { <pending> }"
},
"elapsed": 0.0011802760418504477
},
],
"eventUpdates": {
"4": {
"event": "return",
"thread_id": 0,
"id": 4,
"parent_id": 3,
"return_value": {
"class": "Promise",
"value": "Promise { 'promised return' }"
},
"elapsed": 0.10203119507059455
}
}
}
```
> feat: Capture promise values after they resolve

- src/metadata.ts
- test/__snapshots__/express.test.ts.snap
- test/__snapshots__/jest.test.ts.snap
- test/__snapshots__/mocha.test.ts.snap
- test/__snapshots__/simple.test.ts.snap
- test/__snapshots__/typescript.test.ts.snap
This is what the old agent used to set and apparently some of our tools recognize that name. (Yes, it is all lowercase. I considered casing it properly but I assume the tools case-sensitively look for the literal value.)
> fix: Use "javascript" as the language name in metadata

- README.md
- src/Recording.ts
- src/hooks/http.ts
- src/recorder.ts
- test/__snapshots__/express.test.ts.snap
- test/__snapshots__/sqlite.test.ts.snap
- test/express.test.ts
- test/helpers.ts
- test/sqlite/index.js
> feat: Request recordings

- src/hooks/jest.ts
- src/metadata.ts
- test/__snapshots__/jest.test.ts.snap
- test/jest/test.js
When a test times out, Jest passes a message string back as an error instead of an Error instace. Handle this case.
Fixes #46
@ahtrotta, note the test referred to in #46 still fails because of recording overhead — adjusting timeouts allows it to pass.
> fix: Correctly handle timed out tests in Jest

- src/__tests__/classMap.test.ts
- src/__tests__/helpers.ts
- src/__tests__/registry.test.ts
- src/classMap.ts
- src/event.ts
- src/hooks/__tests__/instrument.test.ts
- src/hooks/instrument.ts
- src/loader.ts
- src/registry.ts
- test/__snapshots__/express.test.ts.snap
- test/__snapshots__/httpClient.test.ts.snap
- test/__snapshots__/jest.test.ts.snap
- test/__snapshots__/mocha.test.ts.snap
- test/__snapshots__/mysql.test.ts.snap
- test/__snapshots__/postgres.test.ts.snap
- test/__snapshots__/simple.test.ts.snap
- test/__snapshots__/sqlite.test.ts.snap
- test/__snapshots__/typescript.test.ts.snap
- test/__snapshots__/vitest.test.ts.snap
Even though they don't have a defining class, appmap tools depend on this field being non-empty. Do the same trick as in classmap and fill it with package name.
> fix: Fill in defined_class field even for free functions

- .github/workflows/ci.yml
- src/hooks/pg.ts
- test/__snapshots__/postgres.test.ts.snap
- test/postgres.test.ts
- test/postgres/index.js
Fixes #64.
Removed proxying Pool.query method because it uses Client.query internally.
> fix: Double sql recording in PostgreSQL

- src/__tests__/recorder.test.ts
- src/parameter.ts
- src/recorder.ts
- test/__snapshots__/httpClient.test.ts.snap
- test/__snapshots__/mysql.test.ts.snap
- test/__snapshots__/postgres.test.ts.snap
- test/__snapshots__/simple.test.ts.snap
- test/__snapshots__/sqlite.test.ts.snap
- test/simple/index.js
Note an event update for a return event for a rejected promise will contain both `exception` and `return_value` fields to disambiguate with the case when the returning function throws an exception directly.
> fix: Handle rejected promises

- src/Recording.ts
- test/simple.test.ts
Some of our tooling watches directories for .appmap.json files and assumes they're well-formed JSON. To avoid confusing them, first stream out the appmap as `.part` file and only rename once it's finished.
> feat: Write AppMaps atomically

- .github/workflows/ci.yml
- package.json
- src/bin.ts
- test/smoketest.mjs
- test/sqlite/index.js
- yarn.lock
This dependency was inadvertently added, but not declared in package.json, leading to problems when run without typescript available. Since it was only used to parse tsconfig.json, it could be replaced by strip-json-comments.
> Remove typescript runtime dependency

- src/Recording.ts
- test/__snapshots__/httpServer.test.ts.snap
- test/__snapshots__/jest.test.ts.snap
- test/__snapshots__/mocha.test.ts.snap
- test/__snapshots__/next.test.ts.snap
- test/__snapshots__/vitest.test.ts.snap
Note this isn't strictly necessary, but allows the paths to be handled more easily eg. with terminal applications making them clickable.
Fixes #94
> feat: Replace spaces in filenames with underscores

- src/__tests__/parameter.test.ts
- src/parameter.ts
Fixes #90. 
Fixes the reported "Maximum call stack size exceeded" problem in the issue, however there is at least one more problem in running cal.com with appmap-node.
> fix: Stack overflow in circularly referenced parameter objects

- package.json
- src/bin.ts
- test/typescript-esm/tsconfig.json
- yarn.lock
Fixes #91
`tsconfig.json` cannot be parsed with `JSON.parse` properly. It can have trailing comma which is not legal in JSON. Use `typescript.readConfigFile` instead.
> fix: Properly parse tsconfig.json

- src/bin.ts
- src/util/NodeOptions.ts
- src/util/__tests__/NodeOptions.test.ts
- test/smoketest.mjs
Fixes #122 
Note: after merging, the workaround should be removed from docs.
> fix: Correctly quote NODE_OPTIONS when spaces occur in paths

- src/Recording.ts
Even though some of the characters are technically legal on some platforms, they might still be inconvenient and inconsistent.
Fixes #134
> fix: Replace special characters in paths consistently on all platforms

- src/__tests__/config.test.ts
- src/config.ts
> fix: Don't replace malformed appmap.yml

- src/hooks/prisma.ts
- test/__snapshots__/prisma.test.ts.snap
- test/prisma/script.js
Fixes #127 
We do two types of Prisma recordings:
1. SQL queries sent to the db as appmap sql query events.
2. Prisma Client Queries (create, findUnique, findMany, ...) as appmap funcion call events.
This fixes two problems reported in #127, that seem to occur with extended Prisma clients.
1. SQLs not recorded.
2. Repeated Prisma Client Queries.
> fix: Prisma recordings on extended Prisma clients

- src/hooks/http.ts
- src/hooks/mongo.ts
- src/hooks/mysql.ts
- src/hooks/sqlite.ts
- src/recorder.ts
- test/jest.test.ts
There was an issue with some generated appmaps, which resulted in the error bellow in the VS Code AppMap viewer - the spinner kept spinning. 
The problem arose from the `parent_id` of certain event update objects (members of the `eventUpdates` array) not matching a call event in the same appmap. In some cases, an appmap had finished, and a new one had been created by the time a promise was resolved, leading to the creation of a fix-up event in the wrong appmap.
This fix verifies whether we are in the correct appmap and skips the fix-up process if not.
> fix: Check if recordings are still active after promise resolution and callbacks

- README.md
- src/__tests__/__snapshots__/config.test.ts.snap
- src/__tests__/config.test.ts
- src/bin.ts
- src/config.ts
- test/__snapshots__/simple.test.ts.snap
- test/codeBlock/appmap.yml
- test/functionLabels/appmap.yml
- test/httpClient/appmap.yml
- test/httpServer/appmap.yml
- test/jest/appmap.yml
- test/libraryCalls/appmap.yml
- test/mocha/appmap.yml
- test/mysql/appmap.yml
- test/next/appmap.yml
- test/prisma/appmap.yml
- test/simple/appmap.yml
- test/sqlite/appmap.yml
- test/typescript-esm/appmap.yml
- test/typescript/appmap.yml
- test/vitest/appmap.yml
By default, this is set to `javascript`. Any existing configurations will be migrated automatically.
> feat: Add `language` to appmap.yml

- src/hooks/http.ts
> fix: Don't block with readFileSync in remote recording finish

- src/__tests__/parameter.test.ts
- src/parameter.ts
This change addresses an issue where exceptions raised by getters during parameter serialization were not handled properly. A test case was added to ensure that the parameter function does not throw an error when encountering a "get" trap, and the `isSimpleObject` function was updated to catch exceptions and return false if an error occurs.
This pull request ensures stability when dealing with objects that have getters that could potentially throw exceptions, preventing crashes and ensuring that such objects are treated as non-simple.
E.g. https://github.com/nestjs/nest/blob/233a89ab3d84d814bb795f738be15216f5b30ed9/packages/common/module-utils/configurable-module.builder.ts#L331-L346
Fixes #158
> fix: Handle exceptions raised by getters during parameter serialization

- src/Recording.ts
- src/__tests__/Recording.test.ts
Fixes #164.
This PR checks if the stream is undefined (AppMap finished or abandoned) when an event is emitted. If so, prevents crash by issuing a warning and omitting the event.
> fix: Crash in emit attempt when stream closed

- src/recorder.ts
This PR updates the interpretation of the `APPMAP_RECORDER_PROCESS_ALWAYS` environment variable so that process recording remains active only if the variable is set to a truthy value (one of ‘true’, ‘1’, ‘on’, ‘yes’).
Previously, the existence of the `APPMAP_RECORDER_PROCESS_ALWAYS` environment variable, regardless of its value, was interpreted as true.
---
Behavior regarding this environment variable is as follows:
When the `APPMAP_RECORDER_PROCESS_ALWAYS` environment variable is not set to one of the truthy values (`true`, `1`, `on`, `yes`), `appmap-node` behaves as follows:
`appmap-node` initially creates a process recording AppMap for the entire process. If `appmap-node` detects a request, a test or a remote recording, it abandons the process recording. Instead, for example, if …
> fix: Check APPMAP_RECORDER_PROCESS_ALWAYS truthy value

- src/config.ts
- src/hooks/__tests__/instrument.test.ts
- src/hooks/instrument.ts
- test/__snapshots__/simple.test.ts.snap
- test/simple.test.ts
- test/simple/global.js
Fixes #159.
This pull request addresses an essential issue by changing instrumentation to prevent potential crashes in environments where `global` or `globalThis` objects are shadowed or manipulated. These updates ensure the stability and reliability of the AppMap recording functionality.
```javascript
function testFun(arg) {
return arg + 1;
}
```
```javascript
function testFun(arg) {
return global.AppMapRecodHook.call(this, () => {
return arg + 1;
}, arguments, __appmapFunctionRegistry[0]);
}
```
```javascript
// These are added to the top of the module/script
function __appmapRecordInit() {
let g = null;
try {
g = global.AppMapRecordHook;
} catch (e) {
try {
g = globalThis.AppMapRecordHook;
} catch (e) {}
// If global/globalThis is shadowed in the top level, we'll get:
// …
```
> fix: Crashes due to shadowed global scope object
